export const BS = {
  btnP: {
    background: "#0B2F4A",
    color: "#fff",
    border: "none",
    padding: "13px 28px",
    fontSize: 12,
    fontFamily: "'Montserrat',sans-serif",
    fontWeight: 700,
    letterSpacing: "0.1em",
    cursor: "pointer",
    borderRadius: 5,
    transition: "all 0.2s",
  },
  btnS: {
    background: "#fff",
    color: "#0B2F4A",
    border: "2px solid #0B2F4A",
    padding: "11px 24px",
    fontSize: 12,
    fontFamily: "'Montserrat',sans-serif",
    fontWeight: 700,
    letterSpacing: "0.1em",
    cursor: "pointer",
    borderRadius: 5,
  },
  btnAccent: {
    background: "#1F7EA6",
    color: "#fff",
    border: "none",
    padding: "13px 28px",
    fontSize: 12,
    fontFamily: "'Montserrat',sans-serif",
    fontWeight: 700,
    letterSpacing: "0.1em",
    cursor: "pointer",
    borderRadius: 5,
  },
  inp: {
    width: "100%",
    border: "1px solid #ddd",
    borderRadius: 6,
    padding: "11px 13px",
    fontSize: 14,
    boxSizing: "border-box",
    marginBottom: 8,
    color: "#333",
    background: "#fff",
  },
  label: {
    fontFamily: "'Montserrat',sans-serif",
    fontSize: 10,
    fontWeight: 700,
    letterSpacing: "0.12em",
    color: "#888",
    marginBottom: 8,
    display: "block",
  },
  card: {
    background: "#f9f9f7",
    borderRadius: 12,
    padding: 22,
    marginBottom: 14,
  },
};
